default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch('DB_PASSWORD') %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: not_sti_development

test:
  <<: *default
  database: not_sti_test

production:
  <<: *default
  database: not_sti_production
  username: not_sti
  password: <%= ENV['DB_PASSWORD'] %>
